---
title: "Tarea - Estructura de datos"
author: "Curso Estadística Descriptiva"
date: "2022-10-14"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Tarea - Estructura de datos


## Pregunta 1
```{r}
harry = -10:27

harry[7]
```
## Pregunta 2
```{r}
n = 0:200
max(100*2^n-7*3^n)

```

## Pregunta 3
```{r}
n = 0:40
x = 3*5^n-1

x[x>3.5]


```

## Pregunta 4

```{r}

comp = function(num){
  c(round(Re(num),2),round(Im(num),2),round(Mod(num),2),round(Arg(num),2) ,round(Conj(num),2))}


```




## Pregunta 5

```{r}

ec = function(A,B,C){
  c((-B + sqrt(B^2 - 4*A*C)/(2*A)),(-B - sqrt(B^2 - 4*A*C)/(2*A)))
}
```

## Pregunta 6

```{r, results='hold'}
 vec = c(0,9,98,2,6,7,5,19,88,20,16,0)

vec[c(2,8,10,11)]
vec[vec == 9 | vec ==19 | vec == 20 | vec == 16]
vec[which(vec == 9 | vec ==19 | vec == 20 | vec == 16)]


```
```{r}
vec[vec%%2==0]
vec[vec%%2==1 && vec>20]
which.max(vec)
which(vec == min(vec))
```
## Pregunta 7

```{r}
A = matrix(c(1,3,2,4),nrow = 2,byrow = TRUE)
A

B = A%*%(A+A)*A
B[2,2]

```
## Pregunta 8
```{r}
C  = rbind(c(2,4,-6),c(0,0,3),c(0,-2,5))

eigen(C)$values
```
## Pregunta 9
```{r}
C = rbind(c(-48,35,-12),c(-134,95,-32),c(-194,133,-44))
print(eigen(C)$vectors,3)
```

## Pregunta 10
```{r}
D = rbind(c(-2,-8,-2,3),c(-3,-6,-1,2),c(-9,-22,-3,7), c(-18,-44,-8,15))
qr(D)$rank
```

